export type PledgeEnvironment = 'production' | 'sandbox';
export type SelectedCharity = { pledgeId:string; name:string; ein?:string; city?:string; state?:string; country?:string; logoUrl?:string; websiteUrl?:string };
export type PledgeSelectionAction = {type:'selected';charity:SelectedCharity}|{type:'removed'};
const UUID_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const isPledgeUuid=(value:unknown):value is string=>typeof value==='string'&&UUID_PATTERN.test(value.trim());
const text=(value:unknown)=>typeof value==='string'&&value.trim()?value.trim():undefined;
const object=(value:unknown):Record<string,unknown>|undefined=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:undefined;
export function getPledgeWidgetConfig(partnerKey:string,environment:PledgeEnvironment='production'){const host=environment==='sandbox'?'https://staging.pledge.to':'https://www.pledge.to';return{partnerKey:partnerKey.trim(),scriptUrl:`${host}/embed/widget.js`,allowedOrigin:host,multipleOrganizations:false}}
export function parsePledgeMessage(event:Pick<MessageEvent,'origin'|'data'>,environment:PledgeEnvironment='production'):PledgeSelectionAction|null{const{allowedOrigin}=getPledgeWidgetConfig('',environment);if(event.origin!==allowedOrigin)return null;let message:unknown=event.data;if(typeof message==='string'){try{message=JSON.parse(message)}catch{return null}}const envelope=object(message);if(!envelope||typeof envelope.action!=='string')return null;if(envelope.action==='removeEvent')return{type:'removed'};if(envelope.action!=='updateEvent')return null;const data=object(envelope.data);if(!data)return null;if(data.beneficiary_type&&data.beneficiary_type!=='Organization')return null;const pledgeId=text(data.beneficiary_uuid)??text(data.organization_id)??text(data.id);if(!isPledgeUuid(pledgeId))return null;const org=object(data.organization);const beneficiary=object(data.beneficiary);return{type:'selected',charity:{pledgeId,name:text(data.organization_name)??text(data.beneficiary_name)??text(data.name)??text(org?.name)??text(beneficiary?.name)??'Selected Pledge nonprofit',ein:text(data.ein)??text(data.ngo_id)??text(org?.ein)??text(org?.ngo_id)??text(beneficiary?.ein)??text(beneficiary?.ngo_id),city:text(data.city)??text(org?.city)??text(beneficiary?.city),state:text(data.state)??text(data.region)??text(org?.state)??text(org?.region)??text(beneficiary?.state)??text(beneficiary?.region),country:text(data.country)??text(data.country_code)??text(org?.country)??text(org?.country_code)??text(beneficiary?.country)??text(beneficiary?.country_code),logoUrl:text(data.logo_url)??text(org?.logo_url)??text(beneficiary?.logo_url),websiteUrl:text(data.website_url)??text(data.website)??text(org?.website_url)??text(org?.website)??text(beneficiary?.website_url)??text(beneficiary?.website)}}}
export const pledgeSelectionReducer=(_current:SelectedCharity|null,action:PledgeSelectionAction):SelectedCharity|null=>action.type==='removed'?null:action.charity;
export function mergeCharityDetails(current:SelectedCharity,details:Partial<SelectedCharity>):SelectedCharity{if(details.pledgeId&&details.pledgeId!==current.pledgeId)return current;return{...current,...Object.fromEntries(Object.entries(details).filter(([,value])=>value!==undefined&&value!=='')),pledgeId:current.pledgeId}}
